var1, var2 = input("Enter two space-separated characters: ").split()
greaterChar = max(var1, var2)
ch1 = ord(var1)
ch2 = ord(var2)
print("-----------------------------")
print(f"The character with greater value is: {greaterChar}")
print("-----------------------------")
print("This part is optional to include.")
print("Showing ASCII Values:")
print(f"{var1} : {ch1}")
print(f"{var2} : {ch2}")